/**
 * Curated shortcode → emoji map for the `:shortcode` composer autocomplete
 * (WhatsApp / Slack style). Not exhaustive — covers the common set. Keys are
 * lowercase shortcodes without colons; `keywords` broadens fuzzy matching so
 * e.g. `:happy` surfaces 😄😁😊 even though none is literally named "happy".
 */

export interface EmojiEntry {
  emoji: string;
  /** Canonical shortcode (without colons). */
  name: string;
  /** Extra search terms that should also match this emoji. */
  keywords?: string[];
}

export const EMOJI_LIST: EmojiEntry[] = [
  // Smileys — happy
  { emoji: '😀', name: 'grinning', keywords: ['happy', 'smile'] },
  { emoji: '😃', name: 'smiley', keywords: ['happy', 'joy'] },
  { emoji: '😄', name: 'smile', keywords: ['happy', 'joy', 'laugh'] },
  { emoji: '😁', name: 'grin', keywords: ['happy'] },
  { emoji: '😆', name: 'laughing', keywords: ['happy', 'haha', 'lol'] },
  { emoji: '😅', name: 'sweat_smile', keywords: ['happy', 'phew'] },
  { emoji: '🤣', name: 'rofl', keywords: ['happy', 'laugh', 'lol', 'lmao'] },
  { emoji: '😂', name: 'joy', keywords: ['happy', 'laugh', 'cry', 'lol'] },
  { emoji: '🙂', name: 'slight_smile', keywords: ['happy'] },
  { emoji: '🙃', name: 'upside_down', keywords: ['silly'] },
  { emoji: '😊', name: 'blush', keywords: ['happy', 'smile'] },
  { emoji: '😇', name: 'innocent', keywords: ['angel', 'happy'] },
  { emoji: '🥰', name: 'smiling_face_with_hearts', keywords: ['love', 'happy'] },
  { emoji: '😍', name: 'heart_eyes', keywords: ['love', 'happy'] },
  { emoji: '🤩', name: 'star_struck', keywords: ['happy', 'wow'] },
  { emoji: '😘', name: 'kissing_heart', keywords: ['love', 'kiss'] },
  { emoji: '😗', name: 'kissing', keywords: ['kiss'] },
  { emoji: '😚', name: 'kissing_closed_eyes', keywords: ['kiss'] },
  { emoji: '😙', name: 'kissing_smiling_eyes', keywords: ['kiss'] },
  { emoji: '😋', name: 'yum', keywords: ['tasty', 'happy'] },
  { emoji: '😛', name: 'stuck_out_tongue', keywords: ['silly'] },
  { emoji: '😜', name: 'stuck_out_tongue_winking_eye', keywords: ['silly', 'wink'] },
  { emoji: '🤪', name: 'zany', keywords: ['silly', 'crazy'] },
  { emoji: '😝', name: 'stuck_out_tongue_closed_eyes', keywords: ['silly'] },
  { emoji: '🤑', name: 'money_mouth', keywords: ['money', 'rich'] },
  { emoji: '🤗', name: 'hugs', keywords: ['hug', 'happy'] },
  { emoji: '🤭', name: 'hand_over_mouth', keywords: ['oops', 'giggle'] },
  { emoji: '🤫', name: 'shushing', keywords: ['quiet', 'shh'] },
  { emoji: '🤔', name: 'thinking', keywords: ['hmm'] },
  { emoji: '😐', name: 'neutral', keywords: ['meh'] },
  { emoji: '😑', name: 'expressionless', keywords: ['meh'] },
  { emoji: '😶', name: 'no_mouth', keywords: ['quiet'] },
  { emoji: '😏', name: 'smirk', keywords: ['smug'] },
  { emoji: '😒', name: 'unamused', keywords: ['meh', 'annoyed'] },
  { emoji: '🙄', name: 'roll_eyes', keywords: ['annoyed'] },
  { emoji: '😬', name: 'grimacing', keywords: ['awkward'] },
  { emoji: '😌', name: 'relieved', keywords: ['calm'] },
  { emoji: '😔', name: 'pensive', keywords: ['sad'] },
  { emoji: '😪', name: 'sleepy', keywords: ['tired'] },
  { emoji: '🤤', name: 'drooling', keywords: ['tasty'] },
  { emoji: '😴', name: 'sleeping', keywords: ['tired', 'zzz'] },
  { emoji: '😷', name: 'mask', keywords: ['sick'] },
  { emoji: '🤒', name: 'thermometer_face', keywords: ['sick'] },
  { emoji: '🤕', name: 'head_bandage', keywords: ['hurt'] },
  { emoji: '🤢', name: 'nauseated', keywords: ['sick', 'gross'] },
  { emoji: '🤮', name: 'vomiting', keywords: ['sick', 'gross'] },
  { emoji: '🤧', name: 'sneezing', keywords: ['sick'] },
  { emoji: '🥵', name: 'hot_face', keywords: ['hot'] },
  { emoji: '🥶', name: 'cold_face', keywords: ['cold'] },
  { emoji: '🥴', name: 'woozy', keywords: ['dizzy'] },
  { emoji: '😵', name: 'dizzy_face', keywords: ['dizzy'] },
  { emoji: '🤯', name: 'exploding_head', keywords: ['mind_blown', 'wow'] },
  { emoji: '🤠', name: 'cowboy', keywords: [] },
  { emoji: '🥳', name: 'partying', keywords: ['party', 'celebrate', 'happy'] },
  { emoji: '😎', name: 'sunglasses', keywords: ['cool'] },
  { emoji: '🤓', name: 'nerd', keywords: ['geek'] },
  { emoji: '🧐', name: 'monocle', keywords: ['thinking'] },
  // Smileys — sad / negative
  { emoji: '😕', name: 'confused', keywords: [] },
  { emoji: '😟', name: 'worried', keywords: ['sad'] },
  { emoji: '🙁', name: 'slight_frown', keywords: ['sad'] },
  { emoji: '☹️', name: 'frowning', keywords: ['sad'] },
  { emoji: '😮', name: 'open_mouth', keywords: ['wow', 'surprised'] },
  { emoji: '😯', name: 'hushed', keywords: ['surprised'] },
  { emoji: '😲', name: 'astonished', keywords: ['wow', 'shocked'] },
  { emoji: '😳', name: 'flushed', keywords: ['embarrassed'] },
  { emoji: '🥺', name: 'pleading', keywords: ['sad', 'please', 'puppy'] },
  { emoji: '😦', name: 'frowning_open', keywords: ['sad'] },
  { emoji: '😧', name: 'anguished', keywords: ['sad'] },
  { emoji: '😨', name: 'fearful', keywords: ['scared'] },
  { emoji: '😰', name: 'cold_sweat', keywords: ['scared', 'nervous'] },
  { emoji: '😥', name: 'disappointed_relieved', keywords: ['sad'] },
  { emoji: '😢', name: 'cry', keywords: ['sad', 'tear'] },
  { emoji: '😭', name: 'sob', keywords: ['sad', 'cry'] },
  { emoji: '😱', name: 'scream', keywords: ['scared', 'shocked'] },
  { emoji: '😖', name: 'confounded', keywords: ['frustrated'] },
  { emoji: '😣', name: 'persevere', keywords: ['struggle'] },
  { emoji: '😞', name: 'disappointed', keywords: ['sad'] },
  { emoji: '😓', name: 'sweat', keywords: ['nervous'] },
  { emoji: '😩', name: 'weary', keywords: ['tired'] },
  { emoji: '😫', name: 'tired_face', keywords: ['tired'] },
  { emoji: '🥱', name: 'yawning', keywords: ['tired', 'bored'] },
  { emoji: '😤', name: 'triumph', keywords: ['angry', 'proud'] },
  { emoji: '😡', name: 'rage', keywords: ['angry', 'mad'] },
  { emoji: '😠', name: 'angry', keywords: ['mad'] },
  { emoji: '🤬', name: 'cursing', keywords: ['angry', 'swear'] },
  { emoji: '😈', name: 'smiling_imp', keywords: ['devil', 'evil'] },
  { emoji: '👿', name: 'imp', keywords: ['devil', 'angry'] },
  { emoji: '💀', name: 'skull', keywords: ['dead'] },
  { emoji: '💩', name: 'poop', keywords: ['poo'] },
  { emoji: '🤡', name: 'clown', keywords: [] },
  { emoji: '👻', name: 'ghost', keywords: ['boo'] },
  { emoji: '👽', name: 'alien', keywords: [] },
  { emoji: '🤖', name: 'robot', keywords: ['bot'] },
  // Gestures / body
  { emoji: '👍', name: 'thumbsup', keywords: ['+1', 'yes', 'like', 'ok'] },
  { emoji: '👎', name: 'thumbsdown', keywords: ['-1', 'no', 'dislike'] },
  { emoji: '👌', name: 'ok_hand', keywords: ['ok', 'perfect'] },
  { emoji: '🤌', name: 'pinched_fingers', keywords: [] },
  { emoji: '✌️', name: 'v', keywords: ['peace', 'victory'] },
  { emoji: '🤞', name: 'crossed_fingers', keywords: ['luck'] },
  { emoji: '🤟', name: 'love_you_gesture', keywords: ['love'] },
  { emoji: '🤘', name: 'metal', keywords: ['rock'] },
  { emoji: '🤙', name: 'call_me', keywords: ['shaka'] },
  { emoji: '👈', name: 'point_left', keywords: [] },
  { emoji: '👉', name: 'point_right', keywords: [] },
  { emoji: '👆', name: 'point_up', keywords: [] },
  { emoji: '👇', name: 'point_down', keywords: [] },
  { emoji: '☝️', name: 'point_up_2', keywords: [] },
  { emoji: '✋', name: 'raised_hand', keywords: ['stop', 'high_five'] },
  { emoji: '🤚', name: 'raised_back_of_hand', keywords: [] },
  { emoji: '🖐️', name: 'hand_splayed', keywords: [] },
  { emoji: '🖖', name: 'vulcan', keywords: ['spock'] },
  { emoji: '👋', name: 'wave', keywords: ['hello', 'hi', 'bye'] },
  { emoji: '🤝', name: 'handshake', keywords: ['deal', 'agree'] },
  { emoji: '👏', name: 'clap', keywords: ['applause', 'bravo'] },
  { emoji: '🙌', name: 'raised_hands', keywords: ['praise', 'celebrate'] },
  { emoji: '👐', name: 'open_hands', keywords: [] },
  { emoji: '🙏', name: 'pray', keywords: ['please', 'thanks', 'thank_you'] },
  { emoji: '🤲', name: 'palms_up', keywords: [] },
  { emoji: '💪', name: 'muscle', keywords: ['strong', 'flex'] },
  { emoji: '✍️', name: 'writing_hand', keywords: ['write'] },
  { emoji: '👀', name: 'eyes', keywords: ['look', 'watch'] },
  { emoji: '🧠', name: 'brain', keywords: ['smart'] },
  // Hearts / symbols
  { emoji: '❤️', name: 'heart', keywords: ['love', 'red_heart'] },
  { emoji: '🧡', name: 'orange_heart', keywords: ['love'] },
  { emoji: '💛', name: 'yellow_heart', keywords: ['love'] },
  { emoji: '💚', name: 'green_heart', keywords: ['love'] },
  { emoji: '💙', name: 'blue_heart', keywords: ['love'] },
  { emoji: '💜', name: 'purple_heart', keywords: ['love'] },
  { emoji: '🖤', name: 'black_heart', keywords: ['love'] },
  { emoji: '🤍', name: 'white_heart', keywords: ['love'] },
  { emoji: '🤎', name: 'brown_heart', keywords: ['love'] },
  { emoji: '💔', name: 'broken_heart', keywords: ['sad', 'heartbreak'] },
  { emoji: '❣️', name: 'heart_exclamation', keywords: ['love'] },
  { emoji: '💕', name: 'two_hearts', keywords: ['love'] },
  { emoji: '💞', name: 'revolving_hearts', keywords: ['love'] },
  { emoji: '💓', name: 'heartbeat', keywords: ['love'] },
  { emoji: '💗', name: 'heartpulse', keywords: ['love'] },
  { emoji: '💖', name: 'sparkling_heart', keywords: ['love'] },
  { emoji: '💘', name: 'cupid', keywords: ['love'] },
  { emoji: '💝', name: 'gift_heart', keywords: ['love'] },
  { emoji: '💯', name: '100', keywords: ['perfect', 'hundred'] },
  { emoji: '💢', name: 'anger', keywords: ['mad'] },
  { emoji: '💥', name: 'boom', keywords: ['explosion'] },
  { emoji: '💫', name: 'dizzy', keywords: ['star'] },
  { emoji: '💦', name: 'sweat_drops', keywords: ['water'] },
  { emoji: '💨', name: 'dash', keywords: ['wind', 'fast'] },
  { emoji: '🔥', name: 'fire', keywords: ['lit', 'hot', 'flame'] },
  { emoji: '⭐', name: 'star', keywords: [] },
  { emoji: '🌟', name: 'star2', keywords: ['glowing'] },
  { emoji: '✨', name: 'sparkles', keywords: ['shiny', 'stars'] },
  { emoji: '⚡', name: 'zap', keywords: ['lightning', 'fast'] },
  { emoji: '☀️', name: 'sunny', keywords: ['sun', 'weather'] },
  { emoji: '🌈', name: 'rainbow', keywords: [] },
  { emoji: '☁️', name: 'cloud', keywords: ['weather'] },
  { emoji: '⛅', name: 'partly_sunny', keywords: ['weather'] },
  { emoji: '❄️', name: 'snowflake', keywords: ['cold', 'winter'] },
  { emoji: '🎉', name: 'tada', keywords: ['party', 'celebrate', 'congrats'] },
  { emoji: '🎊', name: 'confetti_ball', keywords: ['party', 'celebrate'] },
  { emoji: '🎈', name: 'balloon', keywords: ['party'] },
  { emoji: '🎁', name: 'gift', keywords: ['present'] },
  { emoji: '🏆', name: 'trophy', keywords: ['win', 'award'] },
  { emoji: '🥇', name: 'first_place', keywords: ['gold', 'win'] },
  { emoji: '🥈', name: 'second_place', keywords: ['silver'] },
  { emoji: '🥉', name: 'third_place', keywords: ['bronze'] },
  { emoji: '🎯', name: 'dart', keywords: ['target', 'bullseye'] },
  { emoji: '✅', name: 'white_check_mark', keywords: ['check', 'done', 'yes'] },
  { emoji: '☑️', name: 'ballot_box_with_check', keywords: ['check'] },
  { emoji: '✔️', name: 'heavy_check_mark', keywords: ['check', 'done'] },
  { emoji: '❌', name: 'x', keywords: ['no', 'cross', 'wrong'] },
  { emoji: '❎', name: 'negative_squared_cross_mark', keywords: ['no'] },
  { emoji: '⭕', name: 'o', keywords: ['circle'] },
  { emoji: '❓', name: 'question', keywords: ['?'] },
  { emoji: '❗', name: 'exclamation', keywords: ['!'] },
  { emoji: '⚠️', name: 'warning', keywords: ['caution'] },
  { emoji: '🚫', name: 'no_entry_sign', keywords: ['ban', 'stop'] },
  { emoji: '💡', name: 'bulb', keywords: ['idea', 'light'] },
  { emoji: '🔔', name: 'bell', keywords: ['notification'] },
  { emoji: '📌', name: 'pushpin', keywords: ['pin'] },
  { emoji: '📎', name: 'paperclip', keywords: ['attach'] },
  { emoji: '🔗', name: 'link', keywords: [] },
  { emoji: '🔒', name: 'lock', keywords: ['secure'] },
  { emoji: '🔑', name: 'key', keywords: [] },
  { emoji: '💰', name: 'moneybag', keywords: ['money'] },
  { emoji: '💵', name: 'dollar', keywords: ['money'] },
  { emoji: '💳', name: 'credit_card', keywords: ['money', 'card'] },
  { emoji: '📈', name: 'chart_up', keywords: ['stocks', 'growth'] },
  { emoji: '📉', name: 'chart_down', keywords: ['loss'] },
  // Food
  { emoji: '🍎', name: 'apple', keywords: ['fruit'] },
  { emoji: '🍌', name: 'banana', keywords: ['fruit'] },
  { emoji: '🍕', name: 'pizza', keywords: ['food'] },
  { emoji: '🍔', name: 'hamburger', keywords: ['burger', 'food'] },
  { emoji: '🍟', name: 'fries', keywords: ['food'] },
  { emoji: '🌭', name: 'hotdog', keywords: ['food'] },
  { emoji: '🍿', name: 'popcorn', keywords: ['movie', 'food'] },
  { emoji: '🍩', name: 'doughnut', keywords: ['donut', 'food'] },
  { emoji: '🍪', name: 'cookie', keywords: ['food'] },
  { emoji: '🎂', name: 'birthday', keywords: ['cake', 'party'] },
  { emoji: '🍰', name: 'cake', keywords: ['food'] },
  { emoji: '🍫', name: 'chocolate', keywords: ['food'] },
  { emoji: '🍬', name: 'candy', keywords: ['sweet'] },
  { emoji: '☕', name: 'coffee', keywords: ['drink'] },
  { emoji: '🍵', name: 'tea', keywords: ['drink'] },
  { emoji: '🍺', name: 'beer', keywords: ['drink'] },
  { emoji: '🍻', name: 'beers', keywords: ['drink', 'cheers'] },
  { emoji: '🥂', name: 'champagne_glass', keywords: ['cheers', 'celebrate'] },
  { emoji: '🍷', name: 'wine_glass', keywords: ['drink'] },
  // Activities / objects
  { emoji: '⚽', name: 'soccer', keywords: ['football', 'sport'] },
  { emoji: '🏀', name: 'basketball', keywords: ['sport'] },
  { emoji: '🏈', name: 'football', keywords: ['sport'] },
  { emoji: '⚾', name: 'baseball', keywords: ['sport'] },
  { emoji: '🎾', name: 'tennis', keywords: ['sport'] },
  { emoji: '🏏', name: 'cricket', keywords: ['sport'] },
  { emoji: '🎮', name: 'video_game', keywords: ['gaming', 'controller'] },
  { emoji: '🎧', name: 'headphones', keywords: ['music'] },
  { emoji: '🎵', name: 'musical_note', keywords: ['music'] },
  { emoji: '🎶', name: 'notes', keywords: ['music'] },
  { emoji: '📱', name: 'iphone', keywords: ['phone', 'mobile'] },
  { emoji: '💻', name: 'computer', keywords: ['laptop'] },
  { emoji: '⌨️', name: 'keyboard', keywords: [] },
  { emoji: '📚', name: 'books', keywords: ['study', 'read'] },
  { emoji: '📖', name: 'book', keywords: ['read', 'study'] },
  { emoji: '✏️', name: 'pencil2', keywords: ['write', 'edit'] },
  { emoji: '📝', name: 'memo', keywords: ['note', 'write'] },
  { emoji: '🎓', name: 'mortar_board', keywords: ['graduation', 'school', 'grad'] },
  { emoji: '🚀', name: 'rocket', keywords: ['launch', 'fast', 'space'] },
  { emoji: '✈️', name: 'airplane', keywords: ['flight', 'travel'] },
  { emoji: '🚗', name: 'car', keywords: ['drive'] },
  { emoji: '🏠', name: 'house', keywords: ['home'] },
  { emoji: '🌍', name: 'earth_africa', keywords: ['world', 'globe'] },
  { emoji: '💤', name: 'zzz', keywords: ['sleep', 'tired'] },
  { emoji: '💬', name: 'speech_balloon', keywords: ['chat', 'message'] },
  { emoji: '👀', name: 'watching', keywords: ['look'] },
];

/**
 * Search the emoji list by shortcode/keyword prefix. Prefix matches on the
 * canonical name rank first, then keyword matches. Returns up to `max` entries.
 */
export function searchEmojis(query: string, max = 8): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return EMOJI_LIST.slice(0, max);

  const nameStarts: EmojiEntry[] = [];
  const nameIncludes: EmojiEntry[] = [];
  const keywordMatch: EmojiEntry[] = [];
  const seen = new Set<string>();

  for (const e of EMOJI_LIST) {
    if (e.name.startsWith(q)) {
      if (!seen.has(e.emoji)) { nameStarts.push(e); seen.add(e.emoji); }
    } else if (e.name.includes(q)) {
      if (!seen.has(e.emoji)) { nameIncludes.push(e); seen.add(e.emoji); }
    } else if (e.keywords?.some((k) => k.startsWith(q))) {
      if (!seen.has(e.emoji)) { keywordMatch.push(e); seen.add(e.emoji); }
    }
  }

  return [...nameStarts, ...nameIncludes, ...keywordMatch].slice(0, max);
}
